language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

cache: pip

services:
  - mysql

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt



before_script:
  - mysql -e 'create database lurker;'

script:
  - ./tools/pre-tests.sh
  - cd ${TRAVIS_BUILD_DIR}/src
  - python manage.py migrate
  - python manage.py createcachetable
  - coverage run manage.py test


after_success:
  - coveralls


matrix:
  fast_finish: true
